"""
Заполняет отсутствующие task.md реальными заданиями (Python-темы 26-35, остальные позже).
Формат единый: "## Задание N: Заголовок" + описание + пример + подсказка.
Запуск: py scripts/generate_task_content.py
"""

from pathlib import Path

# Скрипт живёт в scripts/, контент — на уровень выше
BASE = Path(__file__).resolve().parent.parent

# folder name -> list of (title, description, example, hint)
PROBLEMS = {
    "26_collections": [
        ("Топ K частых элементов", "Дан массив nums и число k. Верните k наиболее часто встречающихся элементов. Порядок не важен.",
         "nums=[1,1,1,2,2,3], k=2 → [1,2]",
         "Используй collections.Counter + heapq.nlargest (O(n log k))."),
        ("Группа анаграмм", "Дан массив строк strs. Сгруппируйте анаграммы вместе. Верните список групп.",
         "strs=['eat','tea','tan','ate','nat','bat'] → [['bat'],['tan','nat'],['eat','tea','ate']]",
         "Ключ группы — отсортированная строка или tuple(Counter)."),
        ("Палиндром с deque", "Проверьте, является ли строка палиндромом, с учётом только букв и цифр (игнорируя регистр). Реализуйте через collections.deque.",
         "s='A man, a plan, a canal: Panama' → True",
         "Двусторонний deque: pop слева и справа за O(1), сравнивай буквы."),
    ],
    "27_itertools": [
        ("Комбинации", "Дан массив nums и число k. Верните все комбинации по k элементов (без itertools.combinations).",
         "nums=[1,2,3,4], k=2 → [[1,2],[1,3],[1,4],[2,3],[2,4],[3,4]]",
         "Рекурсия + бэктрекинг, либо itertools.combinations для эталона."),
        ("Произведение списков", "Дан список списков. Верните всевозможные произведения их элементов через itertools.product, но без повторений одинаковых кортежей.",
         "[1,2] x [3,4] → [(1,3),(1,4),(2,3),(2,4)]",
         "itertools.product(*lists) + set для дедупликации."),
        ("Бесконечный счётчик", "Создайте кастомный итератор, который бесконечно выдаёт числа 0,1,2,...,n-1,0,1,... (реализуйте через cycle+count или генератор).",
         "первые 7 значений: 0,1,2,3,0,1,2",
         "Напиши генератор с while True и % n; для эталона — itertools.cycle(range(n))."),
    ],
    "28_functools": [
        ("Частичное применение", "Дан список цен и скидка. Через functools.partial сделайте функцию discount(price), возвращающую цену со скидкой, и примените её ко всем ценам.",
         "prices=[100,200,300], скидка 10% → [90,180,270]",
         "partial скидывает фиксированный аргумент: discount = partial(apply_discount, rate=0.1)."),
        ("Мемоизация", "Реализуйте рекурсивную функцию чисел Фибоначчи с кэшированием через functools.lru_cache. Сравните количество вызовов с наивной версией.",
         "fib(30) → 832040, вызовов ≤ 2*n",
         "@lru_cache(maxsize=None) на внутренней функции."),
        ("Редукция", "Дан список чисел. Через functools.reduce найдите максимальный элемент, НЕ используя max().",
         "[3,7,2,9,5] → 9",
         "reduce(lambda a,b: a if a>b else b, nums) или functools.reduce(max, nums)."),
    ],
    "29_python_internals": [
        ("Иммутабельность int/str", "Объясните и продемонстрируйте кодом: почему a = 5; b = a; a = 6 — а остаётся 5? Напишите функцию, которая принимает список и число, меняет список in-place и возвращает новое число.",
         "f([1,2,3], 4) → [1,2,3,4], вернула 4",
         "Целые и строки иммутабельны; списки — мутабельны, передаются по ссылке."),
        ("Замыкания", "Напишите счётчик-замыкание: функция, которая при каждом вызове возвращает 1,2,3,... — используя nonlocal.",
         "increment() три раза → 1, 2, 3",
         "Внутренняя функция + nonlocal count."),
        ("Генераторы: ленивость", "Напишите генератор, который выдаёт первые n простых чисел, не вычисляя все заранее. Покажите, что значения считаются лениво (через yield).",
         "first_n_primes(3) → [2,3,5]",
         "Решето Эратосфена как генератор с yield."),
    ],
    "30_profiling": [
        ("Замер времени", "Дан список из 10^6 чисел. Сравните время создания списка квадратов через list comprehension против for-цикла с append. Верните соотношение.",
         "comprehension обычно в 1.5–2× быстрее",
         "time.perf_counter() вокруг каждой версии, повторите 3 раза, возьмите минимум."),
        ("Найти узкое место", "Дана функция с вложенным циклом: find_duplicates(nums). Профилируйте её через cProfile и найдите функцию-узкое место.",
         "cProfile: большая часть времени — в inner loop",
         "Пиши в файл: python -m cProfile -o out.prof script.py; смотри stats."),
        ("Память", "Измерьте потребление памяти списком из 10^6 целых через tracemalloc. Верните примерный размер в МБ.",
         "~8 МБ (64-бит Python)",
         "tracemalloc.start() → выполни → tracemalloc.get_traced_memory()."),
    ],
    "31_optimization": [
        ("Два указателя", "Дан отсортированный массив. Найдите пару с суммой, равной target, за O(n) через два указателя.",
         "[1,2,3,4,6], target=8 → (2,6)",
         "left=0, right=n-1; двигай left вправо, right влево."),
        ("Хеш вместо цикла", "Дан массив. Найдите первый дубликат за O(n) с O(n) памяти (через set) и верните его индекс.",
         "[2,1,3,2,4] → индекс 3",
         "Классический «уже видели» за O(1) на проверку."),
        ("Пропустить половину", "Дан большой отсортированный массив и target. Найдите индекс target за O(log n) через бинарный поиск (без bisect).",
         "search([1,3,5,7,9], 5) → 2",
         "half = (l + r) // 2, сужай диапазон в два раза."),
    ],
    "32_decorators": [
        ("Таймер-декоратор", "Напишите декоратор @timed, который печатает время выполнения функции в миллисекундах и возвращает результат неизменным.",
         "печать 'slow took 123 ms', вернул результат",
         "functools.wraps(f); time.perf_counter() до и после."),
        ("Логирование вызовов", "Напишите декоратор @logged, который логирует имя функции, аргументы и результат каждого вызова в список LOG.",
         "LOG = []; @logged f(2) → LOG = [('f', (2,), result)]",
         "Декоратор с *args, **kwargs и wrapped.__name__."),
        ("Повтор с задержкой", "Напишите декоратор @retry(times=3, delay=0.1), который повторяет функцию при исключении и пробрасывает ошибку после times попыток.",
         "f бросает ValueError 2 раза подряд, times=3 → 3-я попытка успешна",
         "for i in range(times): try: return f(*a,**kw) except: time.sleep(delay)."),
    ],
    "33_context_managers": [
        ("Файл-менеджер", "Напишите контекстный менеджер open_file(path, mode), который гарантирует закрытие файла, и используйте его с 'with'.",
         "with open_file('tmp.txt','w') as f: f.write('hi') — файл закрыт после",
         "class с __enter__/__exit__ или @contextmanager с yield."),
        ("Таймер как менеджер", "Напишите контекстный менеджер timed_block. В 'with' блоке он измеряет время выполнения и печатает его.",
         "with timed_block(): ...  → 'block took 0.15 s'",
         "@contextmanager: время до yield и после."),
        ("Подавление исключений", "Напишите контекстный менеджер suppress(Exc), который подавляет указанное исключение внутри блока и продолжает выполнение.",
         "with suppress(ValueError): int('abc') — ошибки нет",
         "__exit__ возвращает True при совпадении исключения."),
    ],
    "34_dataclasses": [
        ("dataclass пользователя", "Опишите датакласс User с полями id: int, name: str, email: str и метод full_info()→str. Создайте экземпляр и сравните два экземпляра по равенству.",
         "User(1,'Ann','a@b') == User(1,'Ann','a@b') → True",
         "@dataclass + frozen=True (или eq по умолчанию)."),
        ("Сортировка заказов", "Датакласс Order(id, total: float) снабдите полями так, чтобы сортировка шла по total (убыв.), затем по id (возр.).",
         "sorted(orders) → наибольший total первым",
         "Поле ordering=True + кастомный порядок, либо sorted(key=...)."),
        ("Объединение dataclass", "Напишите функцию merge_users(a: User, b: User), которая возвращает нового User с полями a, но c email=b.email, если email пуст в a.",
         "merge_users(User(1,'A',''), User(2,'B','bb')) → User(1,'A','bb')",
         "dataclasses.replace() или ручное создание."),
    ],
    "35_type_hints": [
        ("Аннотации коллекций", "Аннотируйте функцию group_by_first_letter(words: list[str]) → dict[str, list[str]], группирующую слова по первой букве. Включите Optional и Union где уместно.",
         "Аннотации проходят mypy без ошибок",
         "from __future__ import annotations; dict[str, list[str]], Optional[str]."),
        ("TypedDict для API", "Опишите TypedDict UserResponse с полями id: int, name: str, friends: list[int] и функцию, принимающую объект и возвращающую его имя. Проверьте корректность через mypy.",
         "mypy не ругается на валидный объект и ругается на невалидный",
         "from typing import TypedDict, NotRequired."),
        ("Generics", "Напишите обобщённую функцию first(items: Sequence[T]) → T, возвращающую первый элемент, с TypeVar.",
         "first([1,2]) → 1; first(('a','b')) → 'a'",
         "T = TypeVar('T'); def first(items: Sequence[T]) → T."),
    ],
    "36_sql_select": [
        ("Выборка с условием", "Таблица users(id, name, age). Выберите имена пользователей старше 18 лет, отсортированных по возрасту по убыванию.",
         "SELECT name FROM users WHERE age > 18 ORDER BY age DESC;",
         "WHERE + ORDER BY; экранируй кавычки."),
        ("Подсчёт по группам", "Таблица orders(user_id, amount). Подсчитайте для каждого пользователя суммарную сумму заказов и количество заказов.",
         "SELECT user_id, SUM(amount), COUNT(*) FROM orders GROUP BY user_id;",
         "GROUP BY + агрегатные функции."),
        ("LIMIT и OFFSET", "Таблица products(price). Верните 5 самых дешёвых товаров, исключая первые 10.",
         "SELECT * FROM products ORDER BY price LIMIT 5 OFFSET 10;",
         "ORDER BY price ASC LIMIT/OFFSET."),
    ],
    "37_sql_join": [
        ("INNER JOIN", "Таблицы users(id, name) и orders(id, user_id, amount). Выведите имена и суммы всех заказов.",
         "SELECT u.name, o.amount FROM users u JOIN orders o ON u.id = o.user_id;",
         "INNER JOIN через ON."),
        ("LEFT JOIN + агрегация", "Выведите всех пользователей и суммарную сумму их заказов, включая тех, у кого заказов нет (NULL→0).",
         "SELECT u.name, COALESCE(SUM(o.amount),0) FROM users u LEFT JOIN orders o ON u.id=o.user_id GROUP BY u.name;",
         "LEFT JOIN + COALESCE(...,0)."),
        ("JOIN 3 таблиц", "users, orders, items. Выведите для каждого заказа: имя пользователя и название товара.",
         "SELECT u.name, i.name FROM orders o JOIN users u ON o.user_id=u.id JOIN items i ON o.item_id=i.id;",
         "Двойной JOIN в цепочке."),
    ],
    "38_sql_groupby": [
        ("HAVING", "Таблица sales(category, price). Найдите категории со средней ценой больше 100.",
         "SELECT category, AVG(price) FROM sales GROUP BY category HAVING AVG(price) > 100;",
         "HAVING для фильтра агрегатов (не WHERE)."),
        ("Двойная группировка", "Таблица events(date, platform). Подсчитайте события по дате и платформе.",
         "SELECT date, platform, COUNT(*) FROM events GROUP BY date, platform;",
         "GROUP BY с несколькими колонками."),
        ("Количество уникальных", "Таблица visits(day, user_id). Сколько уникальных пользователей было каждый день?",
         "SELECT day, COUNT(DISTINCT user_id) FROM visits GROUP BY day;",
         "COUNT(DISTINCT ...)."),
    ],
    "39_sql_window": [
        ("ROW_NUMBER", "Таблица students(class_id, score). Для каждого класса пронумеруйте студентов по убыванию балла.",
         "SELECT *, ROW_NUMBER() OVER (PARTITION BY class_id ORDER BY score DESC) rn FROM students;",
         "Оконная функция + PARTITION BY."),
        ("Скользящая сумма", "Таблица sales(day, amount). Для каждого дня посчитайте накопительную сумму продаж.",
         "SELECT day, SUM(amount) OVER (ORDER BY day) FROM sales;",
         "SUM OVER без PARTITION = по всему набору."),
        ("LAG для дельты", "Таблица prices(day, price). Для каждого дня добавьте разницу с предыдущим днём.",
         "SELECT day, price - LAG(price) OVER (ORDER BY day) FROM prices;",
         "LAG(...) OVER (ORDER BY ...)."),
    ],
    "40_indexes": [
        ("Индекс по равенству", "Таблица users(email). Запрос WHERE email='x@y.z' медленный. Что создать для ускорения?",
         "CREATE INDEX idx_users_email ON users(email);",
         "B-tree индекс на колонку поиска."),
        ("Композитный индекс", "Запросы ищут по (country, city). Создайте подходящий индекс.",
         "CREATE INDEX idx_users_country_city ON users(country, city);",
         "Порядок колонок: самый селективный первым."),
        ("Влияние на запись", "Объясните: почему много индексов ускоряют SELECT, но замедляют INSERT/UPDATE?",
         "INSERT обновляет все индексы; баланс чтение/запись",
         "Каждый индекс = доп. структура на запись."),
    ],
    "41_explain": [
        ("Чтение EXPLAIN", "Дан EXPLAIN SELECT ... FROM users WHERE age > 30; Как определить, что есть полный скан таблицы?",
         "type = ALL в плане",
         "Ищи 'type: ALL' (seq scan)."),
        ("Использование индекса", "Почему запрос с LIKE '%text%' не использует обычный индекс на колонке?",
         "LIKE с ведущей звездой — не сработает btree",
         "Полнотекстовый поиск / GIN для подстрок."),
        ("Оптимизация по плану", "EXPLAIN показывает 'Seq Scan' на миллионной таблице с WHERE по колонке x. Что сделать?",
         "Добавить индекс на x и перезапустить ANALYZE",
         "Индекс + VACUUM ANALYZE."),
    ],
    "42_transactions": [
        ("Потерянное обновление", "Две транзакции одновременно увеличивают balance на 10. Опишите проблему и решение (BEGIN/COMMIT/ISOLATION).",
         "Свойство атомарности: UPDATE ... SET balance=balance+10 атомарно",
         "Одиночная UPDATE атомарна; массивы обновлять через row lock."),
        ("Откат", "В транзакции: INSERT, INSERT с ошибкой. Что останется после ROLLBACK?",
         "Ничего: обе вставки откатятся",
         "ROLLBACK отменяет всю транзакцию."),
        ("Уровни изоляции", "Чем READ COMMITTED отличается от REPEATABLE READ? Приведите пример, когда результат различается.",
         "При RC повторные чтения видят чужие коммиты",
         "Опиши ситуацию с двумя соединениями."),
    ],
    "43_redis": [
        ("Кэш с TTL", "Напишите код: сохраните key 'user:1' со значением JSON и временем жизни 60 секунд (redis-py).",
         "r.setex('user:1', 60, json.dumps(user))",
         "setex / SETEX с ttl."),
        ("Счётчик просмотров", "Реализуйте счётчик просмотров поста через INCR, без гонок.",
         "r.incr('post:5:views')",
         "INCR атомарен — не нужны блокировки."),
        ("Очередь через LPUSH/BRPOP", "Реализуйте очередь на Redis: producer (LPUSH) и consumer (BRPOP с таймаутом).",
         "r.brpop('queue', timeout=0)",
         "BRPOP блокирует; потребитель забирает справа."),
    ],
    "44_http": [
        ("Коды ответа", "Для каждой ситуации назовите корректный HTTP-код: 'не найдено', 'нет прав', 'создано', 'валидация не прошла'.",
         "404, 403, 201, 422",
         "Коды: клиентские 4xx, серверные 5xx."),
        ("Заголовки кэша", "Ответ с большим статическим файлом должен кэшироваться на день. Какие заголовки?",
         "Cache-Control: max-age=86400",
         "Cache-Control + ETag/Last-Modified."),
        ("Idempotency", "POST /orders должен быть идемпотентным. Как клиент обеспечивает это?",
         "Передача Idempotency-Key на каждый повтор",
         "Ключ идемпотентности в заголовке."),
    ],
    "45_rest": [
        ("Проектирование ресурсов", "Спроектируйте REST-эндпоинты для блога: создать пост, получить пост, лайк поста, список постов автора.",
         "POST/GET /posts, POST /posts/{id}/like, GET /users/{id}/posts",
         "Существительные, иерархия, методы по действию."),
        ("Пагинация", "Как вернуть 10 000 постов постранично по 25? Какой параметр и зачем limit/offset?",
         "GET /posts?page=2&limit=25",
         "limit/offset или курсор; лимит против перегрузки."),
        ("Версионирование", "Клиент старой версии сломается при изменении /users. Как поддержать обратную совместимость?",
         "GET /v1/users и /v2/users",
         "Версия в пути или в Accept-заголовке."),
    ],
    "46_fastapi": [
        ("Модель Pydantic", "Опишите Pydantic-модель Order с полями id, total, items (список) и валидацией total ≥ 0.",
         "class Order(BaseModel): total: float = Field(ge=0)",
         "BaseModel + Field(ge=0)."),
        ("Эндпоинт с валидацией", "Создайте GET /healthz и POST /tasks, где тело — модель Task(title: str, done: bool=False).",
         "app = FastAPI(); @app.post('/tasks')",
         "FastAPI сам возвращает 422 при невалидном теле."),
        ("Зависимости", "Создайте зависимость get_db(), которая открывает соединение и закрывает его. Примените к эндпоинту.",
         "@app.get('/users')\ndef get_users(db: Session = Depends(get_db))",
         "Depends + yield/генератор в зависимости."),
    ],
    "47_sqlalchemy": [
        ("Модель", "Опишите модель User(id, name, email unique) на SQLAlchemy (declarative).",
         "class User(Base): __tablename__='users'; email = Column(String, unique=True)",
         "Declarative Base + Column."),
        ("Запросы", "Напишите: получить пользователя по email, всех старше 30, первого отсортированного по id.",
         "User.query.filter_by(email=e).first()",
         "filter_by для равенства, order_by/limit."),
        ("Связь один-ко-многим", "Модели User и Post: один пользователь — много постов. Опишите relationship.",
         "posts = relationship('Post', back_populates='user')",
         "ForeignKey + relationship."),
    ],
    "48_docker": [
        ("Dockerfile", "Напишите Dockerfile для Python-приложения: установка зависимостей, копирование кода, запуск uvicorn.",
         "FROM python:3.11-slim\nCOPY requirements.txt .\nRUN pip install -r requirements.txt\nCMD [\"uvicorn\", \"server:app\"]",
         "Слои: базовый → зависимости → код."),
        ("Команды", "Объясните разницу между COPY и ADD, RUN и CMD.",
         "COPY копирует, ADD распаковывает архивы; RUN — build-time, CMD — runtime",
         "Минимальный образ: python:3.11-slim."),
        ("Уменьшение образа", "Образ весит 1.5 ГБ. Какие действия уменьшат его до ~200 МБ?",
         "multi-stage build, python:*-slim, --no-cache-dir",
         "multi-stage + slim + dockerignore."),
    ],
    "49_docker_compose": [
        ("Compose-файл", "Напишите docker-compose.yml: сервисы web (FastAPI) и db (postgres), web зависит от db.",
         "services:\n  web:\n    build: .\n    ports: ['8000:8000']\n  db:\n    image: postgres:16",
         "version, services, ports, depends_on."),
        ("Переменные окружения", "Прокидывайте DATABASE_URL в web-сервис через environment (не хардкодьте в коде).",
         "environment:\n  - DATABASE_URL=postgres://...",
         "12-factor: конфиг в env."),
        ("Масштабирование", "Как запустить 3 реплики web-сервиса? Что нужно изменить (переменные, healthcheck)?",
         "docker compose up --scale web=3",
         "Нужен healthcheck + общие для реплик тома."),
    ],
    "50_cicd": [
        ("Пайплайн CI", "Опишите шаги CI для Python-проекта: линт, тесты, сборка образа, пуша в registry.",
         "lint → test → build → push",
         "Этапы: checkout, setup-python, pip install, pytest, docker build."),
        ("Окружения", "Разделите деплой dev/stage/prod через GitHub Actions: когда какой включается?",
         "dev: push в main; prod: тег v*",
         "triggers: push/branches/tags."),
        ("Кэш зависимостей", "Почему кэш pip в CI экономит минуты? Как его включить в GitHub Actions?",
         "actions/cache с ключом по hash requirements.txt",
         "cache: pip → ~/.cache/pip."),
    ],
    "51_linux": [
        ("Навигация", "Какие команды покажут: текущую папку, список файлов с правами, содержимое файла?",
         "pwd; ls -la; cat file.txt",
         "Утилиты: pwd/ls/cat."),
        ("Поиск и фильтр", "Найдите все .py файлы в /app и посчитайте количество строк в каждом (find, wc).",
         "find /app -name '*.py' -exec wc -l {} \\;",
         "find + -exec."),
        ("Права", "Чем chmod 755 отличается от 644? Для какого типа файлов нужны 755?",
         "755: владелец rwx, группа/другие r-x; 644: rw- для всех",
         "Категории: owner/group/other × r/w/x."),
    ],
    "52_security": [
        ("Инъекции", "Пользователь вводит в поиск: ' OR 1=1; --. Чем опасен такой ввод и как защититься?",
         "SQL-инъекция: параметризуй запросы (не конкатенация)",
         "SQLAlchemy .execute с параметрами."),
        ("Пароли", "Как хранить пароли пользователей безопасно? Почему нельзя sha256 напрямую?",
         "bcrypt/argon2 с солью",
         "хэширование + соль + медленная функция."),
        ("Заголовки", "Перечислите 3 security-заголовка для ответа API и зачем они.",
         "CSP, X-Content-Type-Options, Strict-Transport-Security",
         "Защита XSS/sniffing/понижения."),
    ],
    "53_processes": [
        ("fork vs thread", "Чем многопроцессность отличается от многопоточности в Python (GIL)? Когда что выбирать?",
         "CPU-bound → процессы; I/O-bound → потоки/async",
         "GIL ограничивает параллелизм потоков."),
        ("Управление", "Покажите команды: посмотреть процессы, убить по имени, показать дерево.",
         "ps aux; pkill -f name; pstree",
         "ps/pkill/pstree."),
        ("Демонизация", "Запустите Python-скрипт как демон, чтобы он работал после выхода из терминала (nohup).",
         "nohup python app.py &",
         "nohup + & или setsid."),
    ],
    "54_network": [
        ("Порты", "Какие TCP-порты на 80/443/22/5432/6379 и кому они принадлежат?",
         "HTTP/HTTPS/SSH/PostgreSQL/Redis",
         "Узнаваемые порты."),
        ("Диагностика", "Сервис не отвечает на 8080. Какие команды проверки связи?",
         "ping, netstat -tulpn, curl -v localhost:8080",
         "curl -v покажет подключение/таймаут."),
        ("DNS", "Как проверить, что DNS-имя резолвится, и чем отличается A-запись от CNAME?",
         "dig/nslookup; A = IP, CNAME = имя → имя",
         "dig + типы записей."),
    ],
    "55_files": [
        ("Права и владелец", "Как изменить владельца файла и права на 'чтение-запись только владельцу'?",
         "chown user:group file; chmod 600 file",
         "chown/chmod."),
        ("Симлинки", "Чем симлинк отличается от жёсткой ссылки? Когда использовать ln -s?",
         "symlink: ссылка на путь; hardlink: та же inode",
         "ln -s для удобства, чужой файловой системы."),
        ("Поиск больших файлов", "Найдите 5 самых больших файлов в /var/log и покажите их размер.",
         "du -ah /var/log | sort -rh | head -5",
         "du + sort + head."),
    ],
    "56_logging": [
        ("Конфигурация", "Настройте Python logging: вывод в stdout + файл app.log, формат со временем и уровнем.",
         "logging.basicConfig(level=INFO, handlers=[...])",
         "FileHandler + StreamHandler, формат."),
        ("Уровни", "Когда использовать debug/info/warning/error? Назовите по одному примеру.",
         "debug: подробности; info: значимые события; error: сбой",
         "Уровни по важности."),
        ("Структурированные логи", "Почему JSON-логи лучше текстовых для продакшена и как их сделать?",
         "json.dumps(record) в кастомном Formatter",
         "Парсинг/поиск/агрегация."),
    ],
    "57_metrics": [
        ("Prometheus", "Какие метрики вы бы собирали для HTTP API: счётчики, гистограммы?",
         "http_requests_total, http_request_duration_seconds",
         "Counter + Histogram."),
        ("RED-метрики", "Назовите три метрики для сервиса: Rate, Errors, Duration. Как их измерить?",
         "RPS, error rate, latency (p99)",
         "RED = Rate/Errors/Duration."),
        ("Алерты", "Сформулируйте алерт: '95% запросов медленнее 1 с в течение 5 минут' в PromQL.",
         "histogram_quantile(0.95, rate(...[5m])) > 1",
         "PromQL + alerting rules."),
    ],
    "58_tracing": [
        ("Trace/span", "Объясните разницу между trace, span и log. Как они связаны?",
         "trace = цепочка span; span = единица работы; log = событие внутри",
         "Correlation: trace_id в логах."),
        ("OpenTelemetry", "Как автоматически инструментировать FastAPI-приложение для трейсинга?",
         "opentelemetry-instrumentation-fastapi",
         "SDK + exporter + instrumentation."),
        ("Задержки", "В трейсе видно, что /users занимает 900 мс: 800 мс в span 'db.query'. Что это значит и что делать?",
         "Узкое место — БД: индекс/кэш/пагинация",
         "Читай span-дерево, где основное время."),
    ],
    "59_systemd": [
        ("Unit-файл", "Напишите service-юнит для uvicorn-приложения с рестартом при падении (Restart=always).",
         "[Service]\nExecStart=...\nRestart=always\n[Install]\nWantedBy=multi-user.target",
         "Управление: systemctl enable/start."),
        ("Логи", "Как посмотреть логи сервиса myapp без выхода в файл?",
         "journalctl -u myapp -f",
         "journalctl -u, -f follow."),
        ("Автозапуск", "Чтобы сервис запускался при загрузке ОС, нужно...",
         "systemctl enable myapp",
         "enable создаёт симлинк в multi-user.target."),
    ],
    "60_url_shortener": [
        ("Проектирование", "Спроектируйте URL-shortener: API, модель данных, как генерировать короткие ключи.",
         "POST /shorten {url} → {short}; таблица: key←→url",
         "Key: 6 символов base62, коллизии."),
        ("Идемпотентность", "Один и тот же URL сокращается повторно. Что вернуть: новый ключ или тот же? Как реализовать?",
         "Один ключ на URL: unique-индекс на url",
         "Идемпотентность + дедупликация."),
        ("Перенаправление", "Реализуйте GET /{key}: редирект с кэшированием. Какой HTTP-статус?",
         "302/301 + Cache-Control на ответ",
         "302: временный; 301: постоянный (кэшируется)."),
    ],
    "61_news_feed": [
        ("Модель ленты", "Спроектируйте ленту новостей (feed): какие сущности, как формируется ‘моя лента’?",
         "posts, follows, feed(user) = посты подписок, сортировка по времени",
         "Материализованная лента или фан-аут на чтение."),
        ("Фан-аут", "При публикации поста он должен появиться в ленте 1000 подписчиков. Как доставлять?",
         "фан-аут на запись: push в ленты (Redis/очередь)",
         "Queue + batch push; задержка для больших подписчиков."),
        ("Пагинация ленты", "Лента растёт бесконечно. Как пагинировать без offset-проблем?",
         "Курсор по (user_id, post_time) — ключевая пагинация",
         "Курсор надёжнее OFFSET."),
    ],
    "62_search": [
        ("Индексирование", "Как устроен полнотекстовый поиск по 10M документов? Опишите pipeline.",
         "crawler → нормализация → inverted index",
         "Inverted index: слово → список документов."),
        ("Ранжирование", "Почему простое количество совпадений недостаточно? Что добавить?",
         "TF-IDF, частота, позиция, релевантность",
         "Сначала фильтр, потом ранжирование."),
        ("Поддержка опечаток", "Пользователь печатает 'быстра' вместо 'быстрая'. Как исправить?",
         "Автополнение, редакционное расстояние / n-граммы",
         "Fuzzy match по индексу."),
    ],
    "63_caching": [
        ("Стратегия", "Когда уместен кэш и когда нет? Назовите примеры для 'горячих' и 'холодных' данных.",
         "Горячие данные: частые чтения, редкие записи",
         "Принцип: дешёвое чтение > стоимость инвалидации."),
        ("Инвалидация", "База и кэш рассинхронизировались. Опишите TTL и write-through.",
         "TTL: данные сами устаревают; write-through: пишем в оба",
         "TTL проще, write-through консистентнее."),
        ("Cache stampede", "Кэш истёк, все запросы пошли в БД (каскад). Как защититься?",
         "Лок-блокировка / single-flight + jitter при TTL",
         "Один процесс пересобирает кэш."),
    ],
    "64_queues": [
        ("Работа очереди", "Producer отправляет задачи, worker обрабатывает. Какие гарантии даёт очередь (at-most-once, at-least-once)?",
         "at-least-once: повторная доставка после краха",
         "Идемпотентность обработчиков."),
        ("Задержка задач", "Письмо должно отправиться через 30 минут после регистрации. Как реализовать?",
         "RabbitMQ delayed exchange / Redis ZSET по времени",
         "Отложенные задачи в планировщике."),
        ("Dead letter queue", "Задача падает всегда (битый JSON). Она блокирует очередь. Как её отложить?",
         "Retry с счётчиком → DLQ после N попыток",
         "DLQ + алертинг."),
    ],
    "65_scaling": [
        ("Горизонтальное масштабирование", "API тормозит при 1000 RPS. Что делает горизонтальное масштабирование и какие подводные камни?",
         "Несколько реплик за LB; состояние сессий вне процесса",
         "Stateless API + общий кэш/БД."),
        ("База: шардирование", "Таблица users стала 500M строк. Как разделить по шардам?",
         "Партиционирование/шардирование по user_id (hash/range)",
         "Ключ шарда = хеш, чтобы читать с одного шарда."),
        ("Метрики нагрузки", "Назовите 3 метрики, по которым вы решите, что пора масштабироваться.",
         "CPU/loadavg, p99 latency, error rate",
         "SLO/SLI: 99.9% < 500 мс."),
    ],
    "66_mocks": [
        ("Алгоритм на собесе", "Решите Two Sum за O(n) на бумаге: объясните подход, напишите код, укажите сложность.",
         "дикт: {число: индекс}, O(n)",
         "Объясни до кода."),
        ("Ещё задача", "Найдите k-й наибольший элемент в массиве за O(n log k) (heap).",
         "heapq.nlargest / min-heap размера k",
         "Объясни выбор структуры."),
        ("Обсуждение", "Расскажите про разницу list vs dict по времени операций.",
         "list: O(n) поиск, O(1) append; dict: O(1) get/set",
         "Говори про амортизацию."),
    ],
    "67_mocks2": [
        ("Вопрос по Python", "Что выведет и почему: def f(lst=[]): lst.append(1); return lst — для двух вызовов f()?",
         "[1], затем [1,1] — mutable default",
         "Мутабельный дефолтный аргумент."),
        ("Декоратор на собесе", "Напишите декоратор memoize на бумаге для рекурсивной функции.",
         "кэш {args: result}",
         "functools.lru_cache суть."),
        ("Беседа", "Как бы вы профилировали медленную функцию продакшена?",
         "cProfile/трассировка + гипотезы",
         "Сначала измерь, потом оптимизируй."),
    ],
    "68_mocks3": [
        ("Вопрос по Backend", "Клиент жалуется: POST /orders иногда возвращает 500. Как расследовать?",
         "Логи/трейсы, воспроизведение, метрики",
         "Системный подход: observe → localize."),
        ("SQL на собесе", "Напишите запрос: 3 самых дорогих заказа каждого клиента (оконные функции).",
         "ROW_NUMBER() OVER (PARTITION BY client_id ORDER BY amount DESC) rn; rn <= 3",
         "PARTITION BY + фильтр по rn."),
        ("Системный вопрос", "Чем отличается монолит от микросервисов? Когда микросервисы оправданы?",
         "Команды/масштаб; не спеши с микросервисами",
         "Сначала монолит, потом выделение."),
    ],
    "69_mocks4": [
        ("System design", "Спроектируйте сервис сокращения ссылок (как tinyurl) за 20 минут: функциональные/нефункциональные требования.",
         "POST /shorten, GET /{key}; 1M RPS; latency < 100 мс",
         "Обсуждай требования → дизайн → детали."),
        ("Нагрузка", "Генерация ключей: как избежать коллизий при 100M URL?",
         "base62 из счётчика или hash+проверка",
         "Уникальность + retire."),
        ("Финальный вопрос", "Какие метрики покажут, что сервис деградирует?",
         "Latency p99, error rate, cache hit rate",
         "RED/USE."),
    ],
}

def build_task_md(topic: str, problems: list) -> str:
    """Собрать task.md из списка (title, description, example, hint)."""
    out = [f"# Задания: {topic}", ""]
    for i, (title, desc, example, hint) in enumerate(problems, start=1):
        out.append(f"## Задание {i}: {title}")
        out.append(desc)
        out.append("")
        if example:
            out.append(f"**Пример:** `{example}`")
            out.append("")
        if hint:
            out.append(f"💡 **Подсказка:** {hint}")
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def find_topic_dir(folder: str) -> Path:
    """Найти папку темы в backend/*/ по имени."""
    for block in (BASE / "backend").iterdir():
        if not block.is_dir():
            continue
        candidate = block / folder
        if candidate.is_dir():
            return candidate
    return BASE / "backend" / folder


def main():
    written = 0
    for folder, problems in PROBLEMS.items():
        topic = folder.split("_", 1)[1].replace("_", " ").title()
        topic_dir = find_topic_dir(folder)
        task_md = topic_dir / "task.md"
        task_md.write_text(build_task_md(topic, problems), encoding="utf-8")
        written += 1
        print(f"Updated {folder}")
    print(f"Done: {written} topics written")


if __name__ == "__main__":
    main()